#include "default_css.h"

QString defaultCss()
{
    return "body {"
           "  font-family: Arial, Helvetica, Sans;"
           "  font-size: 11pt;"
           "}"
           ""
           "button {"
           "  background: #ed8f24;"
           "  padding-top: 1em;"
           "  padding-bottom: 1em;"
           "  padding-left: 0.5em;"
           "  padding-right: 0.5em;"
           "  min-width: 50px;"
           "  color: white;"
           "  border: 1px solid #8a5719;"
           "  margin: 2px;"
           "}"
           "button:hover {"
           "  background: #b06919;"
           "}"
           "button:active {"
           "  border-width: 3px;"
           "  margin: 0px;"
           "}"
           "button.disabled {"
           "  background: #909090;"
           "  color: #505050;"
           "  border: 1px solid #606060;"
           "  pointer-events: none;"
           "}"
           "";
}
